### ISSUE TITLE
Issue with using Style 1

### ISSUE THREAD

**Issue by BoxJockey** [kex0/batch-face-swap#1]
Thanks kex0, this is a huge time saver! It works great until I try to use a style I've saved in 'Style 1'. If I do that each image takes progressively more and more time to process. Image 1 will take 2 seconds but the 10th image will take 60 seconds, the 20th will take 5 minutes and the 70th will take 5 hours. Do you have any idea what would cause this?

**Comment by kex0** [comment]
I'm glad it helps!
Sorry but I'm not able to reproduce this issue.

I tried it on a folder with 98 images and with Style 1, Style 2 and both active. The speeds are always the same.
Begining:
![WindowsTerminal_xO7H7IVZvy](https://user-images.githubusercontent.com/46696708/211911267-1f2f2f37-085d-4e43-abaf-76b89aaba413.png)

Towards the end:
![WindowsTerminal_Q3S25csLsG](https://user-images.githubusercontent.com/46696708/211911335-efb2cf4e-adbf-45e6-9787-91d9b993aea2.png)

**Comment by BoxJockey** [comment]
Thanks for checking it out, I'll probably just try a fresh install of Automatic1111.

**Comment by BoxJockey** [comment]
I've re-installed Automatic1111 and now BFS will only work if there is an image in the Inpaint tab. I believe this is due to Automatic1111 redoing the i2i tabs. Does BFS still work for you with Automatic's latest updates?

**Comment by BoxJockey** [comment]
Yep, the Inpaint Upload tab works fine. I finally figured out what was causing my initial problem, Dynamic Prompts. (https://github.com/adieyal/sd-dynamic-prompts) After removing this everything processes normally.
