### ISSUE TITLE
Add option to prefix files with original file name

### ISSUE THREAD

**Issue by SCantan** [kex0/batch-face-swap#11]
Could there be an option to prefix files with the original file name? Like the "Use original name for output filename during batch process in extras tab" option for the extras tab?

The extension works really well and I'm trying to use it to face swap all the faces in an mp4. But since the image files are processed in a non-sequential order, they end up out of order and I can't put them back together as an mp4 again.

Thanks!

**Comment by kex0** [comment]
Done

9aa4a04d9851bcbd5d39ef5e9c7724b9d437fc64

![chrome_hAn2REF6zT](https://user-images.githubusercontent.com/46696708/214695848-5c2f2ab1-9f6e-4481-b020-74ae65879140.png)

It's not prefix though. It just keeps the original name.

**Comment by SCantan** [comment]
Perfect! Thank you!

**Comment by kex0** [comment]
Thank you again for the suggestion! Enjoy
