### ISSUE TITLE
Import existing masks for batch process

### ISSUE THREAD

**Issue by Oem42** [kex0/batch-face-swap#13]
Since afaik there is no way to do a batch job inpainting with a set of paired images and mask images, and since this first makes the mask then runs img2img, would it be possible to  bypass the generation and provide a masks folder and an images folder, with files named the same, and then have this batch process them?

**Comment by kex0** [comment]
Sure, I'll look into it. Thanks for the suggestion.

**Comment by kex0** [comment]
@Oem42 
It is now possible to do this.
You can find it in the new `Existing masks` tab.

![chrome_II7egV6xfJ](https://user-images.githubusercontent.com/46696708/214950920-ddaad87c-bf56-4cd2-a4fb-b07dad674612.png)


1accdc7c4ff4627338a1d5f5be81c096bfb7852d

**Comment by Oem42** [comment]
so something odd is happening.. its clearly loading the mask as its cropping to the right area... but its not applying it
