### ISSUE TITLE
Keep original file name

### ISSUE THREAD

**Issue by BoxJockey** [kex0/batch-face-swap#15]
I'm glad to see 'Keep original file name' added as an option. I like to make batches of 2-4 of each image and choose the best one, and with 'Keep original file name' enabled it produces one image with 2-4 pictures on it. (Which is cool and probably useful for something) But would it be possible to output 'original file name-001' 'original file name-002' 'original file name-003'?

EDIT: Actually, with 'Keep original file name' change BFS now produces a single image with any batch size (all results in one image), regardless if 'Keep original file name' is enabled or not. Hope that makes sense...

**Comment by kex0** [comment]
Hey, I think what you mean is Batch COUNT, if so then you are correct. I forgot to take Batch COUNT to consideration. Batch SIZE always worked.

https://www.youtube.com/watch?v=hnhRKuQgpPU

With the latest commit it should correctly number files with batch count and batch size or combination of the two.
Thank you for the report.
Let me know it it's working as you would expect.

**Comment by BoxJockey** [comment]
Yes, I meant Batch Count, sorry bout that. After updating I get 3 images with a Batch Count of 3, but the first image is all 3 images combined. The second and third images are correct.

**Comment by kex0** [comment]
I'm not sure why is that happening, try disabling this.
![chrome_24e2nn4wl6](https://user-images.githubusercontent.com/46696708/215301409-56378895-a385-4075-b394-c34e87fdacb5.png)

**Comment by BoxJockey** [comment]
I don't have that enabled.

**Comment by kex0** [comment]
I don't know then, it's not happening to me. Maybe some other extension/script?

**Comment by BoxJockey** [comment]
I'll try it without other extentions.

**Comment by kex0** [comment]
Still it doesn't make much sense because this extension completely bypasses regular saving of images that is done by the webui itself.

**Comment by BoxJockey** [comment]
Yea, same results with no other extensions. I'll keep trying different things to see if I can find a reason...

**Comment by kex0** [comment]
1. Does it happen only with one particular image? Or with every image?
2. Is the first "combined" image like the image grid or how are they combined?
3. Does it happen even if you provide a output directory?

**Comment by BoxJockey** [comment]
It happens with all images, even if I provide an output directory. The first image is the image grid (I haven't used that for so long I forgot it was a thing), the second image is the first actual image, so the missing image would be the last of the Batch Count.

**Comment by kex0** [comment]
Try updating the extension and try again.

**Comment by kex0** [comment]
make sure you have the last commit, I made a mistake in [a6a0512](https://github.com/kex0/batch-face-swap/commit/a6a0512044714c386b88ae90f8c2e107976cb807)

commit b01e504995e4c993b46493ec5b1f1c11b74669af

**Comment by BoxJockey** [comment]
That is outputting correctly!

**Comment by BoxJockey** [comment]
Thanks for your time! BFS is exactly what I need so I appreciate it!
