### ISSUE TITLE
image size isn't always preserved properly

### ISSUE THREAD

**Issue by nothings** [kex0/batch-face-swap#18]
It wrote out the image at 512x512, which was also the tile size and which I assume is not a coincidence, but I don't know the cause. If I wan't in the middle of face detection stuff I'd track it down myself.

Note this causes weird stretching of the image. Only happened on some images and not others. Does happen when running this image by itself.

This wasn't happening with the old version from before the compositing change, and I verified this is happening on the current code without my modifications.

Input:
![00484-916853272- the convention floor  at comiccon_0 1  __28yo women with innocent and gorgeous faces and perfect skin  (on the convention floor](https://user-images.githubusercontent.com/7525026/215354379-7099f233-2c23-47e6-9f7a-bdbeb7f2b87c.JPG)

Output:
![00030--1 0-](https://user-images.githubusercontent.com/7525026/215354393-a298520f-2f1d-41a2-9c75-cfd146b62285.png)

<sub>(I know this is a terrible image, I had bad hires fix settings when I made the original. It's part of my face detection test set because of the blurry faces in the background. And the face swapped version was just a quick test that ran for 5 steps.)</sub>

**Comment by nothings** [comment]
Possibly all my other test cases had 0 or 2+ faces, and it's only on the special path for handling 1 face.

**Comment by kex0** [comment]
No matter what I did I couldn't replicate this, unless I used this option.
![chrome_H8KDGnuEdx](https://user-images.githubusercontent.com/46696708/215355493-d801beb7-f9aa-43e4-a24e-c06023288f8d.png)

With latest commit I force this to be at "Only masked" maybe that will fix it?

**Comment by nothings** [comment]
Oh god, yeah, I thought that was being ignored, I usually set it just in case. My bad!
