### ISSUE TITLE
rotate faces to vertical when running SD

### ISSUE THREAD

**Issue by nothings** [kex0/batch-face-swap#27]
One idea in #26 is to rotate the faces so SD proceses a vertical face (since it makes worse faces at other angles), then rotate it back when compositing with the main image.

This seems like a good idea if it can be done easily. Since we use FaceMesh to detect faces, it might be possible to use the info we already get from it to figure out the 3D orientation of the face, figure out the best 2D orientation, and then do the above--but only if we can detect the rotated face in the first place.

**Comment by rubberbaron** [comment]
I would like to work on this.

**Comment by kex0** [comment]
Done in e65f9d0

**Comment by 2blackbar** [comment]
thats great
