### ISSUE TITLE
Inverted mask won't affect the result image

### ISSUE THREAD

**Issue by kraibse** [kex0/batch-face-swap#31]
The mask selecting anything but the body does not apply the generation to the result image. Generating the mask via this script and using it normally with the inpaint upload works as intended.

This is the last working commit:
https://github.com/kex0/batch-face-swap/commit/d729c016fa29cd0ab14e10fd1ee93ce62e37db5b

**Comment by kex0** [comment]
I assume you're talking about inverting mask. 
It's fixed now, thanks for reporting it.
d4249ebd651ce04029701157de5570c951e6c66a

Sorry about that.
