### ISSUE TITLE
Add new parameter for enlarge mask, to generate new head with hair

### ISSUE THREAD

**Issue by Maelstrom2014** [kex0/batch-face-swap#36]
It is possible to make new param for mask padding?
Idea to enlarge mask, to generate new head with hair. Big Thanx!

**Comment by kex0** [comment]
You can change the mask size here V
![chrome_yq9HoOW13p](https://user-images.githubusercontent.com/46696708/236652724-61d87bde-9e9a-4878-baf8-aa6dea19a8db.png)

**Comment by kex0** [comment]
This feature has been greatly improved in 5930ba505698922d676ae8687d5cb6d21cca886f
