### ISSUE TITLE
Problem with masksize blur calculation when mask size is enlarged, border is visible

### ISSUE THREAD

**Issue by 2blackbar** [kex0/batch-face-swap#40]
Guys does it take into consideration the mask size when we set it to +10 or -10 in faceswap panel ? I dont think so

In the code its       p.mask_blur = int(math.ceil(0.01*height))

And when i set it to 10 then i can see straight border were the image ends abruptly
I think the blur should make the seam invisible but i dont think theres code for that currently?
So to the issue hapenns when you use default settings but set mask size to 10 and you get this
![image](https://user-images.githubusercontent.com/33694664/230440715-378dc023-9f22-4ae9-956f-0e520897d504.png)

![image](https://user-images.githubusercontent.com/33694664/230440029-9c5c34ce-656f-4add-abf5-492d2891fbf4.png)

![image](https://user-images.githubusercontent.com/33694664/230440297-0ce1d7c6-3c1d-4934-9b3c-e5636a59ef08.png)

You can see the border of the mask ending abruptly, maybe extra code to fade that out would solve the issue ?
The reason i make the mask bigger is the haircut and hairline, on default 0 the mask border is still visible, i think updated mask blur code should fix this all
There is masking.py in modules folder, i think taking a look how native code blurs the borders would help as well.

**Comment by kex0** [comment]
For some reason I can't reproduce this in any of my photos. Would you mind sending me a photo where this occurs?

**Comment by 2blackbar** [comment]
Sure, also would it be possible so the script would remember the folder with images? In my case i always put images to fix/swap faces in the same folder, it would save time so i dont have to pick the same folder everytime
[0facefix.zip](https://github.com/kex0/batch-face-swap/files/11178963/0facefix.zip)
I ultimately masked faces by hand , couldnt get face swap to do it without mask edges visible and enlarged mask
![00452--1 0-majdz  photo  by kodak   _lora_majdz-4batch-4ep-40rep-32img _0 8_](https://user-images.githubusercontent.com/33694664/230611069-bd1dda10-0b1a-43ab-a399-cb1b8255af96.png)

**Comment by kex0** [comment]
This is what I get with default settings except the mask size, which is at 10
[img2img-images.zip](https://github.com/kex0/batch-face-swap/files/11179051/img2img-images.zip)

**Comment by 2blackbar** [comment]
Looks ok, i wil redownload latest version again

**Comment by kex0** [comment]
I tried on some old version from February and also on the latest. Both gave me the same results.

**Comment by kex0** [comment]
I can replicate your results when I change the `Only masked padding, pixels` to 0
![chrome_4PGglSTvcd](https://user-images.githubusercontent.com/46696708/230630717-5a831dad-fa81-4c78-9b48-344485fa61fd.png)

**Comment by 2blackbar** [comment]
ah, i disable padding steps cause resolution and likeness suffers, is there a chance it will work fine with 0 as well ?

**Comment by kex0** [comment]
Padding is now adjusted automatically
