### ISSUE TITLE
Hello, is it possible to replace the face of the specified picture? It is to input two pictures, one original picture and one selected picture, just like normal face change. I want to change it to be more real, but I have been looking at other projects recently, which are either too fake or take a long time

### ISSUE THREAD

**Issue by anleleaaa** [kex0/batch-face-swap#46]
Hello, is it possible to replace the face of the specified picture? It is to input two pictures, one original picture and one selected picture, just like normal face change. I want to change it to be more real, but I have been looking at other projects recently, which are either too fake or take a long time

**Comment by rubberbaron** [comment]
The purpose of this project is to use Stable Diffusion to generate new faces to replace it.

If you mean you want to use an existing face and have that swapped into another picture, that doesn't involve generating a face with Stable Diffusion, so it's out of scope for this project. There is some experimental ideas for it in #38 but there are no plans to integrate it into the project for real.

If you mean something else, you'll have to rephrase it.
