### ISSUE TITLE
 face mask

### ISSUE THREAD

**Issue by dengtianbi** [kex0/batch-face-swap#50]
Sometimes the range of face detection is not accurate enough, can I provide a face mask by drawing on the UI?

**Comment by kex0** [comment]
Providing mask by drawing is already a feature of the webui in the `Inpaint` tab.

You can try playing with the detector settings or image splitting.
<details>
<summary>Image</summary>
<img src="https://user-images.githubusercontent.com/46696708/236629339-98561c5a-a207-4b6a-9424-0f1ee2f468d3.png">
</details>

Or you can provide existing masks.
<details>
<summary>Image</summary>
<img src="https://user-images.githubusercontent.com/46696708/236629391-14de9213-8957-4b6b-af7f-dd93ac16d158.png">
</details>
