### ISSUE TITLE
convert frames to video

### ISSUE THREAD

**Issue by loboere** [kex0/batch-face-swap#59]
It would be nice to generate a video with the generated frames in the output folder after batch.

I do it with the following code, the frames are arranged in chronological order:
each image is 0001.jpg 0002.jpg etc

```
import cv2
import numpy as np
import glob
size = (55,55)
img_array = []
for filename in sorted(glob.glob('/out_frames/2023-05-18/*')):
    
    img = cv2.imread(filename)
    height, width, layers = img.shape
    size = (width,height)
    img_array.append(img)
    
out = cv2.VideoWriter('project2.avi',cv2.VideoWriter_fourcc(*'DIVX'), 15, size)

for i in range(len(img_array)):
    out.write(img_array[i])
out.release()
```

however I must close the webui, run the code and reopen the webui.
It would be better to generate the video at the end of all the frames.

**Comment by rubberbaron** [comment]
The Automatic1111 UI has multiple places that support batch operations, and it seems like it would make more sense to add that as a general feature than specifically for Batch Face Swap. Mabye a feature for the Extras tab?

**Comment by kex0** [comment]
> The Automatic1111 UI has multiple places that support batch operations, and it seems like it would make more sense to add that as a general feature than specifically for Batch Face Swap. Mabye a feature for the Extras tab?

I agree. Also every video editing software can do that, or you can use [ffmpeg](https://shotstack.io/learn/use-ffmpeg-to-convert-images-to-video/)
