### ISSUE TITLE
Allow us to keep the faces and batch swap the rest of the image

### ISSUE THREAD

**Issue by AncalagonX** [kex0/batch-face-swap#6]
Hello, this is a feature request. I like to take photos of my friends and inpaint their faces into funny or creative scenes like WH40k or the North Korean Navy. Can we invert the face search results so that it inpaint everything except the faces?

Including for cases where there are multiple faces. I would expect it to fuse the individual face detection masks into a single inverted mask that covers the entire source image. Thank you for your time considering this.

**Comment by kex0** [comment]
Sorry for the late reply.

Both inverting the mask and outputting a single mask per image (even with multiple faces) are now possible thanks to you.
d83b961da1b3ef5a18e1b540a5538e52557aec20

Thank you very much for the suggestion.

**Comment by AncalagonX** [comment]
@kex0  It possible thanks to your hard work! Thank you so much for maintaining such an excellent new extension!
