### ISSUE TITLE
Error - The system could not find the specified path.

### ISSUE THREAD

**Issue by mikheys** [kex0/batch-face-swap#64]
Good afternoon. In txt2img, an error constantly pops up and I do not understand how it should work.

![image](https://github.com/kex0/batch-face-swap/assets/34010273/3053cbe1-6050-4793-ac90-58502e8f6c90)

**Comment by kex0** [comment]
Hey,
do you have path here setup correctly?
![chrome_h6OwCX4H8Y](https://github.com/kex0/batch-face-swap/assets/46696708/88310ae8-4606-4810-9be9-280099a6e46a)
