### ISSUE TITLE
I would give it a go BUT...

### ISSUE THREAD

**Issue by sirPhoebus** [kex0/batch-face-swap#8]
I tried to install it but without success ...it does not show up in the img2img with latest updates from automatic1111

Any ideas why ?

**Comment by kex0** [comment]
Sorry for the late reply.

Do you have mediapipe in your venv?
If you installed it through the Extensions tab in webui you should have it and I don't know what could be the issue.
If you didn't, check out the README
I updated it.

**Comment by SpeedOfSpin** [comment]
Make sure you are in the img2img tab also. It will only show up there.
