### ISSUE TITLE
Can it be used to do batch-head-swap?

### ISSUE THREAD

**Issue by SheZ0322** [kex0/batch-face-swap#9]
I wonder if I can do this by expanding the mask?

**Comment by kex0** [comment]
Currently it adjusts the mask size automatically but I'll think about adding some sliders or something tomorrow.

**Comment by SheZ0322** [comment]
Thank you! Have a good night :D

**Comment by kex0** [comment]
I just added this feature.
b9527a0aae4fba4ea5590835e7e43d2f3036c463
Thank you for your suggestion.
